%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 1280
image_height: 720
distortion_parameters:
   k1: -0.0423469
   k2: 0.0115525
   p1: 0
   p2: 0
projection_parameters:
   fx: 1056.85
   fy: 1056.62
   cx: 987.54
   cy: 528.972
